project_id = "avfafxojrijfsgsyimwx"

[functions.check-availability]
verify_jwt = false

[functions.n8n-reservations]
verify_jwt = false

[functions.n8n-appointments]
verify_jwt = false

[functions.n8n-documents]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-connect-product]
verify_jwt = false

[functions.create-connect-checkout]
verify_jwt = false

[functions.list-connect-products]
verify_jwt = false

[functions.stripe-connect-webhook]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = false

[functions.generate-api-key-admin]
verify_jwt = false

[functions.list-salons]
verify_jwt = false

[functions.storefront-salon-detail]
verify_jwt = false

[functions.storefront-book]
verify_jwt = false

[functions.create-storefront-checkout]
verify_jwt = false

[functions.pos-checkout]
verify_jwt = false

[functions.fiskaly-setup]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.storefront-cancel]
verify_jwt = false
